backend:
  name: github
  repo: materiaraiding/materiaraiding
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ingramscloud.workers.dev/

media_folder: "assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "ultimate"
    label: "Ultimate" # Used in the UI
    folder: "_ultimate" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "guide" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "expansion", name: "expansion", widget: "string" }
      - { label: "difficulty", name: "difficulty", widget: "string" }
      - { label: "discussionlink", name: "discussionlink", widget: "string" }
      - { label: "Page Image", name: "image", widget: "string" }
      - { label: "Navigation Order", name: "nav_order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
